### ISSUE TITLE
Add style to front page (html/css)

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/schul-cloud.github.io#13]
We try to mimic the page https://blog.schulcloud.org/ So, we want to be close in style.

Add this to the front page:
- [x] header
- [x] footer
- [x] headings

**Comment by morrme** [comment]
Do you mean you want to mimic https://schulcloud.org/ ?

**Comment by noncototient** [comment]
To clarify, you want this page (https://schul-cloud.github.io/) to mimic this page (https://schulcloud.org/login/) as close as possible?

**Comment by niccokunzmann** [comment]
@noncototient Yes, that is true. The blog part is not so important but if the main page looks similar, this would show that these pages have something to do with each other.
I already started: https://schul-cloud.github.io/dev/

**Comment by noncototient** [comment]
Sweet, can you share a high res screenshot of what the homepage should look like? I am being redirected to login area when I try to access the home page.

**Comment by niccokunzmann** [comment]
@morrme @noncototient Oh! My mistake! I meant this page: https://blog.schulcloud.org/

**Comment by niccokunzmann** [comment]
but the other page can be of inspiration, too. I will change the description above.

**Comment by noncototient** [comment]
It seems that you're pretty much done. All that is left to do is the side navigation, add pagination buttons and make the text red?

**Comment by niccokunzmann** [comment]
Yeah, the blog is "almost" done.

However, if we write files like index.md, currently, no formatting is applied: https://schul-cloud.github.io/

**Comment by jaels** [comment]
Hey! Is this problem still waiting to be solved?

**Comment by niccokunzmann** [comment]
Hi @jaels, yes!
And I think, you can team up with @noncototient.
What would both of you like to do? (header, footer, headings, ...)

If you write it here, there will not be a merge conflict. 
If you create a pull-request soon, we can collaborate.

What are your thoughts?

**Comment by jaels** [comment]
Happily. I'm open to suggestions. That would (potentially) be my first contribute to an open source project so I'm still not very confident with the process and all. Might have some silly questions, like - should I download the project to my machine?

**Comment by niccokunzmann** [comment]
There is reading for you, if you like to pursue it:

- https://desktop.github.com/ - if you like to use the desktop app of github (I recommend it for Windows)
- General Workflow: https://guides.github.com/introduction/flow/index.html
- a 15 minutes git tutorial: http://try.github.io/ if you like to use the console

**Comment by jaels** [comment]
OK, great, thanks! Looking into it

**Comment by niccokunzmann** [comment]
@jaels I created a tutorial for contribution: https://github.com/schul-cloud/schul-cloud.github.io/blob/master/INSTALLING.md
Feel free to change it if you need anything!

**Comment by jaels** [comment]
Great! Thanks so much

**Comment by thakurankit** [comment]
@jaels hey just saw this ...Would it be ok if i could give a shot at the complete thing? Or have to work on specific sections ?

**Comment by jaels** [comment]
Don't entirely understand the question. I've started looking into it and intend to do it. You can look at it as well I guess. Not sure how it works.

**Comment by niccokunzmann** [comment]
@jaels and @thakurankit: working on the footer is almost like working on the header. You can agree on what you want to do and have a look at each other's pull-request. This way, I guess you both can be faster.

How is it going?

**Comment by jaels** [comment]
Sounds good. I'm having some trouble running jekyll

**Comment by jaels** [comment]
OK solved it

**Comment by thakurankit** [comment]
just started working on it...

**Comment by jaels** [comment]
I'll take the header. What do you want inside there?

**Comment by thakurankit** [comment]
so i'll work on the footer.

**Comment by jaels** [comment]
Hey, also got a question: I'm a bit confused - the website that I forked, looking at the content of the HTML, is that one: https://blog.schulcloud.org/
Was expecting to fork the one that needs the improvement, as I understand it. So, this one: 
https://schul-cloud.github.io/
Waiting for your clarification. Thanks

**Comment by noncototient** [comment]
Cool, I'm happy to help. Built a few sites on Jekyll and loved it. Expect a pull request soon :)

**Comment by niccokunzmann** [comment]
@ghost, I think this page can help to understand jekyll: http://jekyll.tips/

The index.md file is written in MarkDown. Jekyll creates HTML from the markdown file. This way, we can focus more on text and less on styling.

I think, the basics can shine a light on this. http://jekyll.tips/
If you have a specific question, please ask like this: "I was trying to ... because I wanted ... but I got ... instead", Then we can help specifically.

**Comment by niccokunzmann** [comment]
@jaels yes, this is what we work on, this repository: https://schul-cloud.github.io/

**Comment by niccokunzmann** [comment]
@ghost @jaels @noncototient I added a [jekyll section](https://github.com/schul-cloud/schul-cloud.github.io/blob/master/INSTALLING.md#how-to-jekyll). Feel free to edit it, fix missing things and add what you found is valuable. It will be valuable for others, too :)

**Comment by niccokunzmann** [comment]
3 answers, now you can reply :)

**Comment by noncototient** [comment]
I've done the blog page and it seems that all styles are already provided by you guys. Can I submit a pull request now?

**Comment by niccokunzmann** [comment]
@noncototient You can sumbit any time. It is #18,I suppose. It was merged. Thanks!

**Comment by jaels** [comment]
If it's still relevant to continue, in the header.html file, in the include folder, the headlines are:
            <h1 class="page-title">Schul-Cloud</h1>
            <h2 class="page-description">In diesem Blog berichten wir über die Arbeit am Pilotprojekt Schul-Cloud. Mehr Infos unter https://hpi.de/schul-cloud</h2>

This is the text from here: https://blog.schulcloud.org/

Was expecting to have the text of this:  https://schul-cloud.github.io/

So, for example, the headline should be: "Entwicklerportal der Schulcloud"

Do I need to copy the text inside?

**Comment by niccokunzmann** [comment]
@jaels You can change

> Schul-Cloud  
> In diesem Blog berichten wir über die Arbeit am Pilotprojekt Schul-Cloud. Mehr Infos unter https://hpi.de/schul-cloud

 to 

> Entwicklerportal der Schulcloud  
> Alles, was du über Schul-Cloud wissen brauchst, um mitzumachen.

You are right - it was copied, pasted and forgotten.

**Comment by jaels** [comment]
Ah, the relevant text is in the index.md file. Should I continue on that or is it already done?

**Comment by jaels** [comment]
OK, thanks, I'll continue. Sorry, got confused

**Comment by niccokunzmann** [comment]
You can add this to the index.md file
```
---
layout: page
---
```
and add a page.html in the _layouts folder. Then, we can use this as the basic layout for any page which is not a blog post.

**Comment by jaels** [comment]
and in the page.html write the full code of the page?

**Comment by niccokunzmann** [comment]
Yes, like the blog-post.html file. https://github.com/schul-cloud/schul-cloud.github.io/blob/master/INSTALLING.md#front-matter

**Comment by jaels** [comment]
Ahhhh ok. Thanks!

**Comment by niccokunzmann** [comment]
Sure. I had not much time to write the INSTALLING.md. So, if you like to add something that would have helped you, you are welcome.

**Comment by jaels** [comment]
So, in the index.html the layout should be "page"?

**Comment by niccokunzmann** [comment]
in the index.md file the layout can be "page".

**Comment by niccokunzmann** [comment]
If you commit and create a pull-request, we can discuss your code, if you like.

**Comment by jaels** [comment]
I still didnt do much. trying to figure out the structure there and markdown and jekyll. If you want to explain it would be great. you're in germany btw?
I could create a pull request. You mean on the forked project?

**Comment by niccokunzmann** [comment]
I am in Germany.
I do not know what to explain. If you commit the code, I can comment and we can see further.

**Comment by niccokunzmann** [comment]
@jaels I found your work and commented. https://github.com/jaels/schul-cloud.github.io/commit/af70695067616022b6624060c0ac16065e40116a#commitcomment-21435406

**Comment by jaels** [comment]
Thanks!!!
Now the page file looks like that:
```
<!DOCTYPE html>
<html {% if page.language %}lang="{{ page.language | escape }}"{% endif %}>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    {{ % include header.html %}}
    {{ page.content }}
    {{ % include footer.html % }}
</body>
</html>
```

But:
1. How would I style it? 
2. Should I copy text into the footer and header from the markdown?

**Comment by jaels** [comment]
3. How can I see the changes without pushing them?

**Comment by niccokunzmann** [comment]
Test it if it works, then create a pull-request, I can merge it and then, I would recommend styling it.

1. You can style it with CSS. Did you use CSS before? We can find tutorials.
2. In general: Copying text should be avoided in programming.
3. `git status` shows the files changes. `git diff` shows all lines changed in a format named "patch". `git diff index.md` - forone file.

**Comment by jaels** [comment]
1. Yeah I know CSS. The question is how to style a markdown text. Should I copy the text from the markdown in to the header?

**Comment by jaels** [comment]
(those were 2 questions actually)

**Comment by niccokunzmann** [comment]
if you run Jekyll, you can go to [index.html](https://schul-cloud.github.io/index.html) at http://localhost:4000
You can have a look at the source code. The Markdown is gone and you have html instead. You can style it with CSS.

**Comment by niccokunzmann** [comment]
I do not know if copying is necessary. This is up to you. If you duplicate all the text, it makes it hard to change in the future.

**Comment by jaels** [comment]
Not duplicate, I meant cut and paste.
The html is what inside the _site folder?

**Comment by niccokunzmann** [comment]
yes, this is what jekyll generated.

**Comment by jaels** [comment]
for some reason it ignored the header and footer. I could also just style it as one file

**Comment by niccokunzmann** [comment]
Did you use `{{` which is for pasting variables or `{%` for executing commands?

**Comment by jaels** [comment]
ok it's fine now :)

**Comment by jaels** [comment]
I need to go for an hour or so. continue when I'm back. thanks so much for all the help until now. will probably need more...

**Comment by jaels** [comment]
Hey are you here?

**Comment by jaels** [comment]
I pushed the header. The font doesnt look 100% identical. Do you also want the menu there?
Have a look.
Can continue working on it if nobody else does.
Still dont quit understand how to give classes etc to the markdown text.

**Comment by niccokunzmann** [comment]
@jaels Can you create a pull-request? It should be possible here: https://github.com/jaels/schul-cloud.github.io/compare

**Comment by jaels** [comment]
created

**Comment by jaels** [comment]
great, first contribution :). should I continue? should I do the body of the text?

**Comment by niccokunzmann** [comment]
You can continue if you like. You can also write a blog post #17 or documentation about what you learned.

**Comment by niccokunzmann** [comment]
@jaels, I updated this comment: https://github.com/schul-cloud/schul-cloud.github.io/issues/13#issuecomment-288422990

**Comment by jaels** [comment]
OK cool. So I would just write a blog post. Do you have more recommendations for easy contributions in javascript/html/css? Or at least some links to where I can find some? 
Thanks again

**Comment by niccokunzmann** [comment]
These are some tutorials, English/German/... http://learn.opentechschool.org/

**Comment by jaels** [comment]
Ah no. I know Javascript etc. Want to contribute to open source project in Github, but to start with the simple tasks

**Comment by niccokunzmann** [comment]
I guess `first-timers-only` is a good issue label to look for. http://makeapullrequest.com/ and up-for-grabs.net

**Comment by jaels** [comment]
Thanks!

**Comment by niccokunzmann** [comment]
Thanks for your contributions! I am closing this now :)
