### ISSUE TITLE
Add People section

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/schul-cloud.github.io#15]
We will have a section for people who wan to contribute to Schul-cloud.
Please add a page for those people.

- [x] it should be styled like https://blog.schulcloud.org/
- [x] it loops through all people in [_data/people.yml](https://github.com/schul-cloud/schul-cloud.github.io/blob/master/_data/people.yml)

Hint: 
- You can get inspiration for showing them from here: http://gci16.fossasia.org/#mentors

**Comment by tekon92** [comment]
#37

**Comment by niccokunzmann** [comment]
@tekon92 Thanks! That would close it in my eyes. Feel free to re-open and comment.

**Comment by tekon92** [comment]
@niccokunzmann where should we put the link of this page?

**Comment by niccokunzmann** [comment]
I think, In the footer is ok, as contributors. What do you think?

**Comment by tekon92** [comment]
yeah i think so.

**Comment by tekon92** [comment]
#39
