### ISSUE TITLE
Add edit link to footer

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/schul-cloud.github.io#16]
If there is something wrong on the web-page or information should be added, it is nice th be able to do this in one click.

- edit button on the bottom linking to the open github page (/edit/)
- show-source button with a github logo linking to the source code
- this  is in _include/footer.html

Hint:
- This is already implemented here: https://niccokunzmann.github.io

**Comment by nadia39** [comment]
I would like contribute to this!
I need to contribute to an open source project for a class.
I only need to change the footer.html file?

**Comment by niccokunzmann** [comment]
I think, so, yes. If you like, please go ahead.
Contribution to open-source in a class .. that is interesting. What class is this?

**Comment by nadia39** [comment]
its for Open Source Software class at university.
I must contribute to an project online.
This one looks interesting, I will work on it now!

**Comment by nadia39** [comment]
Which file is the footer needed for?
Which .html file will it be added to?

**Comment by niccokunzmann** [comment]
Does this answer your question? https://github.com/schul-cloud/schul-cloud.github.io/blob/master/INSTALLING.md (bottom) If not, please tell me, so we can improve the documentation.
