### ISSUE TITLE
Make Blog posts link to each other (HTML/github pages/Jekyll)

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/schul-cloud.github.io#19]
#18 introduced linking blog posts to each other.
This link is the same on all blog posts.
Use Jekyll to link to the following and/or last blog post.

Requirements:
- [x] use the previous and/or last blog post if available
- [x] style it like on https://blog.schulcloud.org/serlo-zum-besuch-beim-schul-cloud-team/

Hints:
- You can see a jekyll implementation [source code](https://github.com/niccokunzmann/niccokunzmann.github.io/blob/master/_layouts/post.html#L40) and [what it looks like](http://niccokunzmann.github.io/blog/2017-03-16/add-badges-to-shields.io)  
  ![image](https://cloud.githubusercontent.com/assets/564768/24189085/f7af233c-0ee3-11e7-9760-e648221bb37c.png)

**Comment by noncototient** [comment]
Do you want the styling to match [these buttons](http://imgur.com/a/IBBmO) or do you want to be like on the screenshot you attached above?

**Comment by niccokunzmann** [comment]
The buttons from above are just an example, so you know what the hint is about.

You added a static blog post at the bottom. Would you like to make this one the link to the other blog post?

**Comment by noncototient** [comment]
My bad! Looked over the second check mark regarding the styling

**Comment by noncototient** [comment]
Should be able to accept the pull request with no conflicts now, #21

**Comment by premshah** [comment]
If this issue is open I will like to claim it

**Comment by niccokunzmann** [comment]
@premshah Yes, it is open. You can work on it. I will try to help you, if you have any questions.

**Comment by niccokunzmann** [comment]
I will check what the current status is, too. #21 is previous work.

**Comment by niccokunzmann** [comment]
Oh no! I recognize, I am satisfied with how the blog posts are linked. However, if you like, you can have a look at it yourself:

- https://schul-cloud.github.io/blog/2017-02-02/kristallklar-mit-der-Schul-Cloud

The links are at the bottom.
I will create more Issues based on what I find on the page. If you like, you can also look for issues.
