### ISSUE TITLE
pr badge und contributing.md

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/schul-cloud.github.io#2]
Auf http://makeapullrequest.com steht, was das Projekt noch so braucht.

- [x] Contributing.md modifizeiren
- [x] README.md mit Bild versehen

**Comment by alaskaa** [comment]
Ich habe die fehlenden Zeilen in die zugehoerigen Dateien eingefuegt! Pull request is pending! 

(Habe bisher nur mit eigenen Github Repos und nicht mit anderen Github Repos gearbeitet - hoffe, ich hab alles richtig gemacht).

**Comment by niccokunzmann** [comment]
#75 Schließt diese Issue. Danke @alaskaa! Wenn du Frgane oder irgendwo Pobleme hast, kannst du gerne fragen. Was magst du weiter machen?

**Comment by alaskaa** [comment]
Erstmal einfache Sachen, damit ich lerne wie man korrekt Pull Requests macht! Werde mich anfangs erstmal an die first-timers-only tags halten :) aber wenn es noch mehr fuer Einsteiger zu tun gibt - her damit!

**Comment by niccokunzmann** [comment]
Gut :)
