### ISSUE TITLE
Add header to blog (HTML/Jekyll)

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/schul-cloud.github.io#23]
Currently, the blog posts do not have a header.
We have a header in the index file.

Please also add this header to the blog posts for a consistent user experience.

Hints: 
- Blogpost: https://schul-cloud.github.io/blog/2017-03-10/technischer-bericht-ver%C3%B6ffentlicht
- Index file: https://schul-cloud.github.io/ and https://github.com/schul-cloud/schul-cloud.github.io/blob/master/index.md
- layouts: https://github.com/schul-cloud/schul-cloud.github.io/tree/master/_layouts
- header: https://github.com/schul-cloud/schul-cloud.github.io/tree/master/_includes

**Comment by bksahu** [comment]
Dibs.

**Comment by bksahu** [comment]
Dibs. :smile:

**Comment by niccokunzmann** [comment]
@bksahu Thanks for your contribution. I noticed that you copied the header from the _includes/header.html file. There is a program command in Jekyll to do this.

    {% include header.html %}

Would you like to try this out, too?
- https://github.com/schul-cloud/schul-cloud.github.io/blob/9302a665764784aa48f53d6a91fac55a2574b2dd/_layouts/page.html#L9

**Comment by bksahu** [comment]
Sure. I would love to do that also.

**Comment by bksahu** [comment]
Sure. I would like to do that also. :smile:

**Comment by niccokunzmann** [comment]
Thanks @bksahu ! Closing this as there are headers everywhere.
