### ISSUE TITLE
Style index file (jekyll, blog)

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/schul-cloud.github.io#24]
Currently, the index file looks like the markdown file.
For some reason it is not rendered properly.

Hints:
- Check the layout and compare it to other layouts.

Links:
- rendered version: https://schul-cloud.github.io/
- source: https://github.com/schul-cloud/schul-cloud.github.io/blob/master/index.md

**Comment by tekon92** [comment]
#31 remove enter on the top

**Comment by niccokunzmann** [comment]
It works now. Closing this. Feel free to open again or create a new issue.
