### ISSUE TITLE
Add blog post about how to add a blog post

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/schul-cloud.github.io#25]
This makes it easier for new-comers to contribute.

In the [/dev/_posts][posts] directory, you can find files for the blog post.

Please create a new one and explain the following:

- How you use git and github
- How to add your user name to the [_data/people.yml](https://github.com/schul-cloud/schul-cloud.github.io/blob/master/_data/people.yml) file.
- What goes into the header?
- Where and how to add the blog post.

Please use Markdown and the post layout, see other posts.
If you have any questions, please ask.

[posts]: https://github.com/schul-cloud/schul-cloud.github.io/tree/master/dev/_posts

**Comment by tekon92** [comment]
#31

**Comment by niccokunzmann** [comment]
I think, your pull-request satisfies all requirements. Closing this issue therefore. Thanks!
