### ISSUE TITLE
Add Impressum Link (Git/Github/HTML)

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/schul-cloud.github.io#36]
There was a link to the Impressum - a page required by the German law <https://dejure.org/gesetze/TMG/5.html> to show who is behind the site and how to contact the person. A [pull-request removed the link](https://github.com/schul-cloud/schul-cloud.github.io/pull/34/files#diff-7693eb643e8fe8b8d46b407909b408ce).
Please add the link to the page again.

**Comment by niccokunzmann** [comment]
@tekon92 The impressum is something different from the contributors page. If we use http://hpi.de/impressum we can be sure that it has the right form and content and the admins of Schul-Cloud can be reached.

**Comment by tekon92** [comment]
@niccokunzmann so which on is impressum link? this one http://hpi.de/impressum ?

**Comment by tekon92** [comment]
#39

**Comment by niccokunzmann** [comment]
@tekon92 correct. Thanks!
