### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by maddin2016** [schul-cloud/schul-cloud.github.io#41]
Hello everyone,
I have read a lot about this project and it sounds really exciting. I also have two kids (7 and 9) and i want to ask if there is way to contribute to this project. Maybe for `schulcloud-server` or `schulcloud-client`. Let me know if there is something to do.

**Comment by niccokunzmann** [comment]
Hi, I am glad you commented.
We have lots of things to work on. They are in a Trello which is still closed.
I think, we can get issues out of there which the @schul-cloud/bp Bachelorproject does not have as a priority - I just talked to them.
One thing they assinged to me is translation: Currently, the Client is German only. I am not proficient in node, so if you want to work on this or have ideas, ... schul-cloud/schulcloud-client#173

In general: We want to go towards a process which is more transparent an allows people to contribute.
This means:
- If you spot anything that could make it easier,  you can open an issue/create a pull-request
- You CAN write a blogpost at [schul-cloud.github.io/dev](https://github.com/schul-cloud/schul-cloud.github.io/tree/master/dev/_posts) about what you did to contribute or create documentation. We want to document it and this will help focus on what is important.

@kremer-io Do you have thoughts on this?

**Comment by niccokunzmann** [comment]
I created #43 which you can follow and improve to setup Schul-Cloud. Currently, I want to improve the documentation to make getting started easier.

**Comment by maddin2016** [comment]
Hi @niccokunzmann,
thanks for the PR. I will see what i can do. Can you tell me a little bit about the project. You can also ping me by E-Mail.

**Comment by niccokunzmann** [comment]
Hi @maddin2016 can I do anything else for you, if not, I will close this in s couple of days.
I think, we were in contact vie e-mail. If you are looking for more opportunities, please let me know :)
