### ISSUE TITLE
Remove "ss" to "ß" conversion (CSS)

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/schul-cloud.github.io#42]
![grafik](https://cloud.githubusercontent.com/assets/564768/25267849/c2e1f8f0-2676-11e7-858a-aeb07c823990.png)

@nicoknoll suggested this must be removed to remove the error:

    -webkit-font-feature-settings: 'dlig' 1, 'liga' 1, 'lnum' 1, 'kern' 1;

**Comment by nicoknoll** [comment]
And the same for "-ms-" and "-moz-" prefixes

**Comment by niccokunzmann** [comment]
@nicoknoll Can you have a look? It seems like @jprberlin corrected it.

**Comment by niccokunzmann** [comment]
@nicoknoll Is this resolved?

**Comment by pradyunsg** [comment]
Looks like it's been fixed.

**Comment by niccokunzmann** [comment]
So, I am closing it. If someone disagrees, we can re-open.
