### ISSUE TITLE
Font is not correctly displayed in Chrome (MacOS)

### ISSUE THREAD

**Issue by HDinger** [schul-cloud/schul-cloud.github.io#51]
When opening https://schul-cloud.github.io with Chrome on Mac every `ss` is displayed as `ß` (e.g. 'ißues' or 'wißen'). This seems to be caused by the font family.

**Comment by niccokunzmann** [comment]
Thanks for reporting this. Let's proceed in #42. If I mistakenly think this is a duplicate, please re-open.
