### ISSUE TITLE
How to setup the development environment in Visual Studios 17

### ISSUE THREAD

**Issue by VijayVj7** [schul-cloud/schul-cloud.github.io#58]
1)Could you please create a tutorial on how to create the dev env in visual studios 17, it would be really helpful for first timers like me..!! 

2)I've cloned your project in VS 17, but stuck in setting up the environment. 
   Not getting from where to start
Please help us !! 
Hope you come back with a solution
![image](https://cloud.githubusercontent.com/assets/18487229/26119450/df5e2f1c-3a8a-11e7-9022-c25581c386c0.png)

**Comment by niccokunzmann** [comment]
Hi, I will take a deeper look tomorrow. (0:00 almost here). My question is: which projects would you like to contribute to? If I help you set it up, would you write down your steps to create a small tutorial? I may not really write it as you like to hear it. Let's see.

**Comment by VijayVj7** [comment]
Hi Nicco,

Apologies for delay in reply.Firstly, I would like to contribute to the
front-end part of the project.Thats the reason I've asked you to create a
small tutorial for the dev env setup.

Hope you revert back soon

**Comment by niccokunzmann** [comment]
Hi, I see. Currently we only have the setup covered for Ubuntu.
https://schul-cloud.github.io/blog/2017-04-21/setup-development-under-ubuntu
I think, after I thought a while ^^, that you need a tutorial for Windows.

I will not do it today but I hope, tomorrow.
The steps would be like those from the ubuntu tutorial but with the commands different for the installation of node and mongodb.

Also, we have an issue that we need a docker setup for development. This would work under Windows, too. https://github.com/schul-cloud/schul-cloud.github.io/issues/49
@kremer-io may have thougts on it.

**Comment by niccokunzmann** [comment]
We are working on a tutorial for Windows.

**Comment by niccokunzmann** [comment]
@VijayVj7 In #59 I introduce the windows setup. Please try to do the setup. If there are any problems, write them down, so others have an easier start.

**Comment by niccokunzmann** [comment]
@VijayVj7 It is online, now. https://schul-cloud.github.io/blog/2017-05-18/setup-schul-cloud-client-and-sever-under-windows

**Comment by niccokunzmann** [comment]
@VijayVj7 Since I did not hear anything from you, I will close this now. Feel free to open another issue or comment below :)
