### ISSUE TITLE
Link to repositories

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/schul-cloud.github.io#60]
On the first page, you can view services and their build statuses.
Please make the service name a link to the repository of the service.

**Comment by hristo-tanev** [comment]
Hi there, can I get on with this issue? Thanks ;)!

**Comment by niccokunzmann** [comment]
@hristo-tanev Sure, please go ahead! Your contributions are welcome.

**Comment by alaskaa** [comment]
Is this still open? Or has it been resolved?

**Comment by niccokunzmann** [comment]
It is still open.
